# Generated by Django 5.2.5 on 2025-08-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número da Máquina')),
                ('capacity_liters', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidade (Litros)')),
                ('mold_dim_c', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dimensão C (Molde)')),
                ('mold_dim_a', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dimensão A (Molde)')),
                ('mold_dim_l', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dimensão L (Molde)')),
            ],
        ),
        migrations.CreateModel(
            name='Pn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('pn_code', models.CharField(max_length=50, unique=True, verbose_name='PN')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('type_piece', models.CharField(max_length=50, verbose_name='Tipo')),
                ('property', models.CharField(max_length=50, verbose_name='Propriedade')),
                ('capacity_liters', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidade (Litros)')),
                ('min_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Mín (Kg)')),
                ('max_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Máx (Kg)')),
                ('sold_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Vendido (Kg)')),
                ('cycle_time_seconds', models.IntegerField(verbose_name='Tempo de Ciclo (segundos)')),
                ('cavity', models.IntegerField(verbose_name='Cavidade')),
                ('dim_c', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dimensão C')),
                ('dim_a', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dimensão A')),
                ('dim_l', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dimensão L')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('delivery_date', models.DateField(verbose_name='Data de Entrega')),
                ('pn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.pn', verbose_name='PN')),
            ],
        ),
    ]
