# Generated by Django 5.2.5 on 2025-08-19 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquina',
            options={'verbose_name': 'Máquina', 'verbose_name_plural': 'Máquinas'},
        ),
        migrations.AlterModelOptions(
            name='ordemproducao',
            options={'verbose_name': 'Ordem de Produção', 'verbose_name_plural': 'Ordens de Produção'},
        ),
        migrations.AlterModelOptions(
            name='pn',
            options={'verbose_name': 'PN', 'verbose_name_plural': 'Part Numbers'},
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_planejada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Planejamento'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Fim'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Início'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.maquina', verbose_name='Máquina Planejada'),
        ),
    ]
