# Generated by Django 5.2.5 on 2025-08-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_alter_maquina_options_alter_ordemproducao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pn',
            options={'permissions': [('can_view_planejamento', 'Pode visualizar a página de planejamento')], 'verbose_name': 'PN', 'verbose_name_plural': 'Part Numbers'},
        ),
    ]
