# Generated by Django 5.2.5 on 2025-08-25 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_alter_pn_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Início do Agendamento')),
                ('end_datetime', models.DateTimeField(verbose_name='Fim do Agendamento')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.maquina', verbose_name='Máquina')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.ordemproducao', verbose_name='Ordem de Produção')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'unique_together': {('ordem_producao',)},
            },
        ),
    ]
