# Generated by Django 5.2.5 on 2025-08-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemproducao',
            name='data_planejada',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='maquina',
        ),
    ]
