# Generated by Django 5.2.5 on 2025-08-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_remove_ordemproducao_data_planejada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Planejada', 'Planejada'), ('Em Produção', 'Em Produção'), ('Concluída', 'Concluída')], default='Disponível', max_length=20, verbose_name='Status'),
        ),
    ]
