# Generated by Django 5.2.5 on 2025-08-31 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0006_ordemproducao_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='quantidade_produzida',
            field=models.IntegerField(default=0, verbose_name='Quantidade Produzida'),
        ),
        migrations.CreateModel(
            name='ApontamentoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade Apontada')),
                ('data_apontamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Apontamento')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='producao.agendamento')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo da Parada')),
                ('inicio_parada', models.DateTimeField(auto_now_add=True, verbose_name='Início da Parada')),
                ('fim_parada', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Parada')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='producao.agendamento')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
