# Generated by Django 5.2.5 on 2025-08-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0007_ordemproducao_quantidade_produzida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pn',
            options={'permissions': [('can_view_planejamento', 'Pode visualizar a página de planejamento'), ('can_view_producao', 'Pode visualizar a tela de produção')], 'verbose_name': 'PN', 'verbose_name_plural': 'Part Numbers'},
        ),
    ]
