# Generated by Django 5.2.5 on 2025-08-31 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0008_alter_pn_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código da Parada')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Parada',
                'verbose_name_plural': 'Tipos de Parada',
            },
        ),
        migrations.RemoveField(
            model_name='parada',
            name='motivo',
        ),
        migrations.AddField(
            model_name='parada',
            name='tipo_parada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.tipoparada', verbose_name='Tipo de Parada'),
        ),
    ]
