# Generated by Django 5.2.5 on 2025-08-31 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0009_tipoparada_remove_parada_motivo_parada_tipo_parada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='fim_parada',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 31, 23, 42, 23, 238474, tzinfo=datetime.timezone.utc), verbose_name='Fim da Parada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parada',
            name='inicio_parada',
            field=models.DateTimeField(verbose_name='Início da Parada'),
        ),
    ]
