# Generated by Django 5.2.5 on 2025-10-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0010_alter_parada_fim_parada_alter_parada_inicio_parada'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='lado',
            field=models.CharField(blank=True, choices=[('L', 'Esquerdo'), ('R', 'Direito')], max_length=1, null=True),
        ),
    ]
