# Generated by Django 5.2.5 on 2025-10-19 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0011_agendamento_lado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRefugo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código do Refugo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Refugo',
                'verbose_name_plural': 'Tipos de Refugo',
            },
        ),
        migrations.CreateModel(
            name='Refugo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade Refugada')),
                ('data_apontamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Apontamento')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refugos', to='producao.agendamento')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_refugo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.tiporefugo', verbose_name='Tipo de Refugo')),
            ],
            options={
                'verbose_name': 'Apontamento de Refugo',
                'verbose_name_plural': 'Apontamentos de Refugo',
            },
        ),
    ]
