# Generated by Django 5.2.5 on 2025-11-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0012_tiporefugo_refugo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pn',
            options={'permissions': [('can_view_planejamento', 'Pode visualizar a página de planejamento'), ('can_view_producao', 'Pode visualizar a tela de produção'), ('can_view_gerenciamento', 'Pode visualizar a tela de gerenciamento')], 'verbose_name': 'PN', 'verbose_name_plural': 'Part Numbers'},
        ),
    ]
