# Generated by Django 5.2.5 on 2025-11-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0013_alter_pn_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='real_start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início Real da Produção'),
        ),
    ]
