# Generated by Django 5.2.5 on 2025-11-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0014_agendamento_real_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoparada',
            name='classificacao_parada',
            field=models.CharField(blank=True, choices=[('PLANEJADA', 'Planejada (Não conta no OEE)'), ('NÃO PLANEJADA', 'Não Planejada (Perda de Disponibilidade)')], help_text='Classifique se esta parada é uma perda (Não Planejada) ou parte da rotina (Planejada).', max_length=20, null=True, verbose_name='Classificação OEE'),
        ),
    ]
